"""Generate `~/.codex/config.toml` so Codex routes through the Paritok proxy.

Codex does not honor `OPENAI_BASE_URL`; its endpoint comes only from a custom
`model_provider` in `~/.codex/config.toml`. Rather than make users hand-write
TOML, `paritok up`/`proxy` writes it from the `codex:` block in paritok.yaml when
`codex.enabled` is true — so the whole setup lives in one file.

Codex custom providers support only the `responses` wire protocol (which the
proxy serves at `/v1/responses`), and have no literal api_key field, so the key
is embedded as `experimental_bearer_token` (or left to `env_key` when blank).
"""

from __future__ import annotations

import shutil
from pathlib import Path

from paritok.config import CodexConfig


def _toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_codex_config(cfg: CodexConfig, host: str, port: int) -> str:
    """Render the config.toml body pointing Codex at the proxy."""
    # 0.0.0.0 is a bind address, not a dial address — Codex must connect to a real host.
    dial_host = "127.0.0.1" if host in ("0.0.0.0", "::", "") else host
    base_url = f"http://{dial_host}:{port}/v1"

    lines = [
        "# Generated by `paritok up`/`proxy` from the codex: block in paritok.yaml.",
        "# Edit paritok.yaml and restart the proxy to regenerate; manual edits here are overwritten.",
        f'model = "{_toml_escape(cfg.model)}"',
        'model_provider = "paritok"',
        "",
        "[model_providers.paritok]",
        'name = "paritok"',
        f'base_url = "{base_url}"',
        'wire_api = "responses"',
    ]
    if cfg.api_key:
        lines.append(f'experimental_bearer_token = "{_toml_escape(cfg.api_key)}"')
    else:
        # No key in paritok.yaml → Codex reads it from the environment instead.
        lines.append('env_key = "OPENAI_API_KEY"')
    return "\n".join(lines) + "\n"


def write_codex_config(cfg: CodexConfig, host: str, port: int) -> Path:
    """Write the generated config.toml, backing up any existing (non-generated) one.

    Returns the path written.
    """
    target = Path(cfg.config_path).expanduser() if cfg.config_path \
        else Path.home() / ".codex" / "config.toml"
    target.parent.mkdir(parents=True, exist_ok=True)

    body = render_codex_config(cfg, host, port)

    if target.exists():
        existing = target.read_text(encoding="utf-8", errors="replace")
        if existing == body:
            return target  # already up to date, nothing to do
        # Only back up a file we didn't generate, so we never clobber a user's own config silently.
        if "Generated by `paritok" not in existing:
            backup = target.with_suffix(target.suffix + ".paritok-bak")
            shutil.copy2(target, backup)

    target.write_text(body, encoding="utf-8")
    return target
